import type { Metadata } from "next";
import { Iceberg, Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({
  variable:"--font-inter",
  subsets:["latin"],
  weight:["400","500","600"]
});

const iceberg = Iceberg({
  weight:"400",
  variable:"--heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${iceberg.variable} antialiased flex justify-center gap-2`}
      >
        <aside className="w-max h-screen sticky top-0 left-0">
          <Sidebar/>
        </aside>
        <main className="w-full max-h-screen overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
